"""
app/models/schemas.py — Pydantic models for all API and internal data structures.
"""
from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


# ─── Phi Router Output ──────────────────────────────────────────────────────

class PhiClassification(BaseModel):
    """
    Structured output from the Phi router model when classifying a newly uploaded document.
    Phi returns this strict JSON structure to suggest the destination vault and auto-generate metadata.
    """
    vault: str
    confidence: float = Field(ge=0.0, le=1.0)
    tags: list[str] = []
    media_type: str = "text"
    summary: str = ""
    extra_meta: dict[str, Any] = {}


class VaultScore(BaseModel):
    """Individual vault confidence score assigned by the Phi router during a query search."""
    vault_name: str
    confidence: float = Field(ge=0.0, le=1.0)


class PhiQueryRoute(BaseModel):
    """
    Ranked array of vaults returned by Phi when routing a user's question.
    Determines which vaults should actually be searched for context.
    """
    vaults: list[VaultScore]
    decomposed_queries: list[str] = []  # sub-queries if it's a compound question


# ─── Source & Answer Objects ────────────────────────────────────────────────

class SourceChunk(BaseModel):
    """Represents a single piece of retrieved context from the sqlite-vec database."""
    chunk_id: str
    vault_name: str
    source_file: str
    page_number: int | None = None
    text_snippet: str
    distance: float                    # cosine distance from the user's query
    media_type: str = "text"


class ConflictFlag(BaseModel):
    """Flag generated by Llama 3.1 if two retrieved chunks contradict each other."""
    chunk_a_id: str
    chunk_b_id: str
    description: str


class GeneratedAnswer(BaseModel):
    """Final answer object produced by the RAG generation pipeline."""
    answer: str
    sources: list[SourceChunk] = []
    vault_attribution: list[str] = []
    conflicts: list[ConflictFlag] = []


# ─── Vault Metadata ─────────────────────────────────────────────────────────

class VaultInfo(BaseModel):
    """Metadata and statistics for a single vault, stored in the vault registry."""
    name: str
    doc_count: int = 0
    chunk_count: int = 0
    topic_summary: str = ""
    key_themes: list[str] = []
    coverage_gaps: list[str] = []
    last_updated: str | None = None


class Registry(BaseModel):
    """The root structure of the `registry.json` file storing all known vaults."""
    vaults: dict[str, VaultInfo] = {}


# ─── FastAPI Request / Response ─────────────────────────────────────────────

class QueryRequest(BaseModel):
    """Payload for POST /query"""
    query: str
    vault_name: str | None = None     # None = use Phi auto-route
    global_search: bool = False       # True = bypass Phi, search ALL vaults
    session_id: str = "default"


class QueryResponse(BaseModel):
    """Response payload for POST /query"""
    answer: str
    sources: list[SourceChunk] = []
    vault_attribution: list[str] = []
    conflicts: list[ConflictFlag] = []
    routing_confidence: float | None = None


class IngestRequest(BaseModel):
    """Payload for POST /ingest"""
    vault_name: str
    file_path: str                    # local file path generated by API server


class IngestResponse(BaseModel):
    """Response payload for POST /ingest"""
    vault_name: str
    source_file: str
    chunks_inserted: int


class VaultCreateRequest(BaseModel):
    """Payload for POST /vaults"""
    name: str
    topic_summary: str = ""


class VaultDeleteRequest(BaseModel):
    """Payload for DELETE /vaults/{name}"""
    name: str
    confirm: bool = False


class HealthResponse(BaseModel):
    """Response payload for GET /health"""
    status: Literal["ok", "error"] = "ok"
    ollama_reachable: bool = False
    db_path: str = ""
    vault_count: int = 0
    total_chunks: int = 0


# ─── Learning System ─────────────────────────────────────────────────────────

class CorrectionRecord(BaseModel):
    """A log entry recorded when a user overrides Phi's suggested vault classification."""
    original_input: str               # filename or query
    phi_suggestion: str
    phi_confidence: float
    user_choice: str
    timestamp: str


class UserRule(BaseModel):
    """An automatically extracted static rule overriding Phi based on historical corrections."""
    trigger_keywords: list[str]
    correct_vault: str
    not_vault: str | None = None
    confidence: float = 1.0
    generated_from: int = 0           # number of corrections that aggregated into this rule


class UserRules(BaseModel):
    """The root structure of the `user_rules.json` file."""
    rules: list[UserRule] = []


# Fix forward reference for Pydantic v2
PhiQueryRoute.model_rebuild()
